linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - prealloc
    - revive

linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US
  gosec:
    excludes:
      - G204  # Разрешить exec.Command

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - scripts
    - docs

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0